name: DB Migrate (Supabase)

on:
  workflow_dispatch:
    inputs:
      apply:
        description: "Apply migrations to Supabase (true/false)"
        required: true
        default: "true"

jobs:
  migrate:
    if: ${{ github.event.inputs.apply == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install psql client
        run: |
          sudo apt-get update -y
          sudo apt-get install -y postgresql-client

      - name: Preflight connectivity (owner)
        env:
          SUPABASE_DB_OWNER_URL: ${{ secrets.SUPABASE_DB_OWNER_URL }}
        run: |
          if [ -z "$SUPABASE_DB_OWNER_URL" ]; then echo "Missing secret SUPABASE_DB_OWNER_URL" && exit 1; fi
          psql "$SUPABASE_DB_OWNER_URL" -c "select current_user, current_database();"
          psql "$SUPABASE_DB_OWNER_URL" -c "select tableowner from pg_tables where schemaname='storage' and tablename='objects';"

      - name: Run storage policies migration (psql)
        env:
          SUPABASE_DB_OWNER_URL: ${{ secrets.SUPABASE_DB_OWNER_URL }}
        run: |
          psql "$SUPABASE_DB_OWNER_URL" -v ON_ERROR_STOP=1 -f supabase/migrations/20250907170000_add_storage_policies.sql

      - name: Optimize RLS auth calls (psql)
        env:
          SUPABASE_DB_OWNER_URL: ${{ secrets.SUPABASE_DB_OWNER_URL }}
        run: |
          psql "$SUPABASE_DB_OWNER_URL" -v ON_ERROR_STOP=1 -f supabase/migrations/20250907173500_optimize_rls_auth_calls.sql

      - name: Verify storage policies present
        env:
          SUPABASE_DB_OWNER_URL: ${{ secrets.SUPABASE_DB_OWNER_URL }}
        run: |
          psql "$SUPABASE_DB_OWNER_URL" -c "select polname, cmd from pg_policies where schemaname='storage' and tablename='objects' order by polname;"
